version: '3'
services:
  frontend:
    container_name: hippo-guest-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
      - /usr/src/app/frontend/.next
  backend:
    container_name: hippo-guest-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules